AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Account:
    Type: String
    Description: Account name (who is this for?)
  PreviousVersionArchive:
    Type: Number
    MinValue: 30
    Default: 30
    Description: Number of days before archiving a previous version of a template to Glacier
  CurrentVersionArchive:
    Type: Number
    MinValue: 30
    Default: 30
    Description: Number of days before archiving the current version of a template to IA storage class
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Join [ "-", [ !Ref 'AWS::AccountId', !Ref 'AWS::Region', !Ref Account, 'cloudformation', 'templates' ] ]
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
        - Id: 'ArchiveOldVersions'
          Status: Enabled
          NoncurrentVersionTransitions:
          - StorageClass: GLACIER
            TransitionInDays: !Ref PreviousVersionArchive
          Transitions:
          - StorageClass: STANDARD_IA
            TransitionInDays: !Ref CurrentVersionArchive
      Tags:
      - Key: Account
        Value: !Ref Account
  S3User:
    DependsOn: S3Bucket
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: !Sub "CoreTemplatesS3UserPolicy-${Account}"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "s3:DeleteObject"
                  - "s3:GetBucketLocation"
                  - "s3:GetObject"
                  - "s3:GetObjectAcl"
                  - "s3:GetObjectTagging"
                  - "s3:ListBucket"
                  - "s3:PutObject"
                  - "s3:PutObjectTagging"
                Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"
              - Effect: Allow
                Action: [ "s3:ListBucket" ]
                Resource: !Sub "arn:aws:s3:::${S3Bucket}"
      UserName: !Sub "S3CoreTemplates-${Account}"
  S3UserAccessKey:
    DependsOn: S3User
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref S3User
Outputs:
  PreviousVersionArchive:
    Value: !Ref PreviousVersionArchive
    Description: Number of days before archiving a previous version of a template to Glacier
  CurrentVersionArchive:
    Value: !Ref CurrentVersionArchive
    Description: Number of days before archiving the current version of a template to IA storage class
  BucketName:
    Value: !Ref S3Bucket
    Description: Name of the sample Amazon S3 bucket with a lifecycle configuration.
  S3UserName:
    Value: !Ref S3User
    Description: Build artifacts username
  S3UserARN:
    Value: !GetAtt S3User.Arn
    Description: Build artifacts user ARN
  UserAccessKeyID:
    Value: !Ref S3UserAccessKey
    Description: The access key ID for the build artifacts user
  UserAccessKeySecret:
    Value: !GetAtt S3UserAccessKey.SecretAccessKey
    Description: The secret key for the build artifacts user